// internal/sdd/linter/installer.go
package linter

import (
	"fmt"
	"os"
	"path/filepath"
)

const assumptionLinterScript = `#!/usr/bin/env bash
# assumption-linter.sh — auto-generated by architect-ai
set -euo pipefail
CHANGE="${1:?change_name required}"
ARTIFACT_DIR="openspec/changes/${CHANGE}"
VIOLATIONS=0
[ ! -d "${ARTIFACT_DIR}" ] && { echo "WARN: ${ARTIFACT_DIR} not found"; exit 0; }
while IFS= read -r -d '' file; do
  grep -nqE '\b!!G A P!!\b|\bTo Be Determined\b' "${file}" 2>/dev/null && {
    echo "VIOLATION !!G A P!!: ${file}"; VIOLATIONS=$((VIOLATIONS+1)); }
  grep -nqE '\bFixMe\b|\bTo-Do\b' "${file}" 2>/dev/null && {
    echo "VIOLATION FixMe/To-Do: ${file}"; VIOLATIONS=$((VIOLATIONS+1)); }
  grep -q "Source of Truth:" "${file}" 2>/dev/null || {
    echo "VIOLATION TRACE: ${file}"; VIOLATIONS=$((VIOLATIONS+1)); }
done < <(find "${ARTIFACT_DIR}" -name "*.md" -print0 2>/dev/null)
[ "${VIOLATIONS}" -gt 0 ] && { echo "FAIL: ${VIOLATIONS} violation(s)"; exit 1; }
echo "PASS"
`

const validateContractScript = `#!/usr/bin/env bash
# validate-result-contract.sh — auto-generated by architect-ai
set -euo pipefail
RESULT=$(cat)
python3 -c "
import json, sys
data = json.loads(sys.argv[1])
required = ['status','phase','executive_summary','artifacts','next_recommended','risks','skill_resolution']
missing = [f for f in required if f not in data]
if missing:
    print('INVALID: missing fields:', missing)
    sys.exit(1)
valid_statuses = ['completed','failed','blocked','abandoned']
if data.get('status') not in valid_statuses:
    print('INVALID: status must be one of', valid_statuses)
    sys.exit(1)
sr = data.get('skill_resolution', {})
if not isinstance(sr, dict) or 'status' not in sr:
    print('INVALID: skill_resolution.status missing')
    sys.exit(1)
print('VALID')
" "${RESULT}"
`

// InstallScripts writes linter scripts to .atl/scripts/
func InstallScripts(atDir string) error {
	scriptsDir := filepath.Join(atDir, "scripts")
	if err := os.MkdirAll(scriptsDir, 0755); err != nil {
		return fmt.Errorf("create scripts dir: %w", err)
	}

	scripts := map[string]string{
		"assumption-linter.sh":          assumptionLinterScript,
		"validate-result-contract.sh":   validateContractScript,
	}

	for name, content := range scripts {
		path := filepath.Join(scriptsDir, name)
		if err := os.WriteFile(path, []byte(content), 0755); err != nil {
			return fmt.Errorf("write %s: %w", name, err)
		}
	}
	return nil
}
