// Code generated by generate-agent-metering.sh — DO NOT EDIT by hand.
// Regenerate from the delta package after updating provider shapes.
package kiro


import (
	"github.com/rd-mg/architect-ai/internal/agents/claude"
	"github.com/rd-mg/architect-ai/internal/metering"
)

// Kiro speaks Claude Messages API natively; delegate to Claude parser.
func ExtractUsage(raw []byte) (metering.UsageDelta, error) {
	return claude.ExtractUsage(raw)
}

func SessionHookEnabled() bool { return true }

func RecordResponse(raw []byte) {
	claude.RecordResponse(raw)
}

