// Code generated by generate-agent-metering.sh — DO NOT EDIT by hand.
// Regenerate from the delta package after updating provider shapes.
package cursor


import (
	"bytes"
	"fmt"

	"github.com/rd-mg/architect-ai/internal/agents/claude"
	"github.com/rd-mg/architect-ai/internal/agents/codex"
	"github.com/rd-mg/architect-ai/internal/agents/gemini"
	"github.com/rd-mg/architect-ai/internal/metering"
)

// ExtractUsage sniffs the response shape and dispatches to the right parser.
// Cursor supports multiple underlying providers; the Composer decides at runtime.
func ExtractUsage(raw []byte) (metering.UsageDelta, error) {
	switch {
	case bytes.Contains(raw, []byte(`"cache_read_input_tokens"`)):
		return claude.ExtractUsage(raw)
	case bytes.Contains(raw, []byte(`"usageMetadata"`)):
		return gemini.ExtractUsage(raw)
	case bytes.Contains(raw, []byte(`"prompt_tokens_details"`)):
		return codex.ExtractUsage(raw)
	}
	return metering.UsageDelta{}, fmt.Errorf("cursor: unknown provider response shape")
}

func SessionHookEnabled() bool { return true }

func RecordResponse(raw []byte) {
	hook := metering.Current()
	if hook == nil {
		return
	}
	delta, err := ExtractUsage(raw)
	if err != nil {
		return
	}
	hook.Record(delta)
}

