package setup

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/rd-mg/architect-ai/internal/platform"
)

// EnsureContextMode checks if context-mode is installed and installs it if not.
func EnsureContextMode(dryRun bool) (string, error) {
	// Check if already installed
	out, err := exec.Command("context-mode", "--version").Output()
	if err == nil {
		return strings.TrimSpace(string(out)), nil
	}

	// Not installed — install it
	fmt.Println("Installing context-mode...")
	if dryRun {
		fmt.Println("  DRY RUN: would run: npm install -g context-mode")
		return "dry-run", nil
	}

	cmd := exec.Command("npm", "install", "-g", "context-mode")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("npm install -g context-mode failed: %w", err)
	}

	// Get version after install
	out, err = exec.Command("context-mode", "--version").Output()
	if err != nil {
		return "installed", nil
	}
	return strings.TrimSpace(string(out)), nil
}

// ConfigurePlatform writes all config files for the given platform.
func ConfigurePlatform(p platform.Platform) ([]string, error) {
	var written []string

	for _, cf := range p.ConfigFiles {
		path := expandHome(cf.Path)
		dir := filepath.Dir(path)

		if err := os.MkdirAll(dir, 0755); err != nil {
			return written, fmt.Errorf("cannot create dir %s: %w", dir, err)
		}

		var content string
		if cf.Merge && isJSON(path) {
			// Merge JSON
			merged, err := mergeJSON(path, cf.Content)
			if err != nil {
				return written, fmt.Errorf("cannot merge %s: %w", path, err)
			}
			content = merged
		} else {
			content = cf.Content
		}

		if err := atomicWrite(path, content); err != nil {
			return written, fmt.Errorf("cannot write %s: %w", path, err)
		}
		written = append(written, path)
	}

	// Copy routing file if required
	if p.RoutingFileRequired && p.RoutingFile != "" {
		routingSource := findContextModeConfig(p)
		if routingSource != "" {
			data, err := os.ReadFile(routingSource)
			if err == nil {
				if err := atomicWrite(p.RoutingFile, string(data)); err == nil {
					written = append(written, p.RoutingFile)
				}
			}
		}
	}

	return written, nil
}

// DryRunPlatform returns the list of files that would be written for a platform.
func DryRunPlatform(p platform.Platform) []string {
	var files []string
	for _, cf := range p.ConfigFiles {
		files = append(files, cf.Path)
	}
	if p.RoutingFileRequired && p.RoutingFile != "" {
		files = append(files, p.RoutingFile)
	}
	return files
}

// WritePlatformConfig writes .atl/platform-config.yaml.
func WritePlatformConfig(p platform.Platform, cmVersion string) error {
	if err := os.MkdirAll(".atl", 0755); err != nil {
		return err
	}

	content := fmt.Sprintf(`# architect-ai platform configuration
# Generated by: architect-ai setup
# Do not edit manually — run: architect-ai setup

platform: %s
context_mode:
  installed: true
  version: "%s"
  hook_level: "%s"
  mcp_tools:
    - ctx_execute
    - ctx_batch_execute
    - ctx_execute_file
    - ctx_index
    - ctx_search
    - ctx_fetch_and_index
    - ctx_stats
    - ctx_doctor
    - ctx_upgrade
    - ctx_purge
    - ctx_insight
`, p.Name, cmVersion, string(p.HookLevel))

	return atomicWrite(".atl/platform-config.yaml", content)
}

// mergeJSON merges newContent into existing JSON file, preferring new values.
func mergeJSON(path, newContent string) (string, error) {
	existing := make(map[string]interface{})
	if data, err := os.ReadFile(path); err == nil {
		json.Unmarshal(data, &existing)
	}

	newData := make(map[string]interface{})
	if err := json.Unmarshal([]byte(newContent), &newData); err != nil {
		return "", err
	}

	// Deep merge
	for k, v := range newData {
		if existingMap, ok := existing[k].(map[string]interface{}); ok {
			if newMap, ok := v.(map[string]interface{}); ok {
				for nk, nv := range newMap {
					existingMap[nk] = nv
				}
				existing[k] = existingMap
				continue
			}
		}
		existing[k] = v
	}

	merged, err := json.MarshalIndent(existing, "", "  ")
	if err != nil {
		return "", err
	}
	return string(merged), nil
}

func expandHome(path string) string {
	if strings.HasPrefix(path, "~/") {
		home, err := os.UserHomeDir()
		if err == nil {
			return filepath.Join(home, path[2:])
		}
	}
	return path
}

func isJSON(path string) bool {
	return strings.HasSuffix(path, ".json")
}

func findContextModeConfig(p platform.Platform) string {
	// Look for context-mode config directory in common locations
	candidates := []string{
		filepath.Join(os.Getenv("HOME"), "node_modules", "context-mode", "configs", p.Name, p.RoutingFile),
		filepath.Join(os.Getenv("HOME"), ".npm", "context-mode", "configs", p.Name, p.RoutingFile),
	}
	for _, c := range candidates {
		if _, err := os.Stat(c); err == nil {
			return c
		}
	}
	return ""
}

func atomicWrite(path, content string) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
