// Code generated by generate-agent-metering.sh — DO NOT EDIT by hand.
// Regenerate from the delta package after updating provider shapes.
package gemini


import (
	"encoding/json"

	"github.com/rd-mg/architect-ai/internal/metering"
)

type geminiUsageEnvelope struct {
	UsageMetadata struct {
		PromptTokenCount        int64 `json:"promptTokenCount"`
		CandidatesTokenCount    int64 `json:"candidatesTokenCount"`
		CachedContentTokenCount int64 `json:"cachedContentTokenCount"`
	} `json:"usageMetadata"`
	ModelVersion string `json:"modelVersion"`
}

func ExtractUsage(raw []byte) (metering.UsageDelta, error) {
	var env geminiUsageEnvelope
	if err := json.Unmarshal(raw, &env); err != nil {
		return metering.UsageDelta{}, err
	}
	return metering.UsageDelta{
		PromptTokens:     env.UsageMetadata.PromptTokenCount,
		CompletionTokens: env.UsageMetadata.CandidatesTokenCount,
		CachedTokens:     env.UsageMetadata.CachedContentTokenCount,
		CacheCreated:     0, // Gemini does not distinguish cache_creation.
		Model:            env.ModelVersion,
	}, nil
}

func SessionHookEnabled() bool { return true }

func RecordResponse(raw []byte) {
	hook := metering.Current()
	if hook == nil {
		return
	}
	delta, err := ExtractUsage(raw)
	if err != nil {
		return
	}
	hook.Record(delta)
}

