package mcp

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func WriteSecretsEnv(projectDir string, secrets map[string]string) error {
	envPath := filepath.Join(projectDir, ".env.mcp")
	ensureGitignored(filepath.Join(projectDir, ".gitignore"), ".env.mcp")
	existing := readDotEnv(envPath)
	for k, v := range secrets { existing[k] = v }
	var lines []string
	lines = append(lines, "# MCP Secrets — generated by architect-ai", "# DO NOT COMMIT — gitignored", "")
	for k, v := range existing { lines = append(lines, fmt.Sprintf("%s=%s", k, v)) }
	return os.WriteFile(envPath, []byte(strings.Join(lines, "\n")+"\n"), 0600)
}

func readDotEnv(path string) map[string]string {
	result := make(map[string]string)
	f, err := os.Open(path)
	if err != nil { return result }
	defer f.Close()
	s := bufio.NewScanner(f)
	for s.Scan() {
		line := strings.TrimSpace(s.Text())
		if line == "" || strings.HasPrefix(line, "#") { continue }
		if parts := strings.SplitN(line, "=", 2); len(parts) == 2 {
			result[parts[0]] = parts[1]
		}
	}
	return result
}

func ensureGitignored(path, pattern string) {
	data, _ := os.ReadFile(path)
	if gitignoreCovers(string(data), pattern) {
		return
	}

	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return
	}
	defer f.Close()
	fmt.Fprintf(f, "\n# MCP secrets — do not commit\n%s\n", pattern)
}

func gitignoreCovers(content, pattern string) bool {
	for _, rawLine := range strings.Split(content, "\n") {
		line := strings.TrimSpace(rawLine)
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "!") {
			continue
		}
		if line == pattern {
			return true
		}
		if matched, err := filepath.Match(line, pattern); err == nil && matched {
			return true
		}
	}
	return false
}

func WriteConfig(targetPath string, config map[string]interface{}) error {
	data, err := json.MarshalIndent(config, "", "  ")
	if err != nil { return fmt.Errorf("marshal: %w", err) }
	tmp := targetPath + ".tmp"
	if err := os.MkdirAll(filepath.Dir(targetPath), 0755); err != nil { return fmt.Errorf("mkdir: %w", err) }
	if err := os.WriteFile(tmp, data, 0644); err != nil { return fmt.Errorf("write tmp: %w", err) }
	return os.Rename(tmp, targetPath)
}
