package architect

import (
	"fmt"
	"time"
)

func RoutingRulesMarkdown() string {
	return fmt.Sprintf(`## L0 Routing Rules — Auto-Generated from GoLib
<!-- DO NOT EDIT — generated by internal/architect/routing_rules.go -->
<!-- Last generated: %s -->

### IMMUTABILITY RULE — L0 is a Pure Router

L0 NEVER executes any tool directly. Zero exceptions.

### Routing Decision

ALL tasks route to L1 (L0 never executes inline):

| Task Type | Route | L1 Agent |
|---|---|---|
| SDD intent (/sdd-*, spec, apply, design) | Mode B | sdd-orchestrator (L1a) |
| Everything else (including git, grep, cat) | Mode C | general-orchestrator (L1b) |

Mode A (inline execution) does NOT exist in this architecture.
It was removed in v0.3 because L0 inline execution:
  1. Elevates D4 artificially in subsequent L1 delegations
  2. Violates the Strict Isolation Rule between L1a and L1b
  3. Undermines the 4-file rule enforcement

### SDD Intent Detection

A message is SDD_INTENT if it matches ANY of:
  - Starts with /sdd-
  - Contains: "write a spec", "design this", "implement", "apply changes", "create tasks"
  - Regex: \b(spec|design|implement|apply|sdd)\b.*\b(this|the|a|an)\b

When in doubt: route to general-orchestrator (Mode C).
Never execute inline when in doubt.
`, time.Now().UTC().Format("2006-01-02"))
}
