// Code generated by generate-agent-metering.sh — DO NOT EDIT by hand.
// Regenerate from the delta package after updating provider shapes.
package qwen


import (
	"github.com/rd-mg/architect-ai/internal/agents/codex"
	"github.com/rd-mg/architect-ai/internal/metering"
)

// Qwen uses OpenAI-compatible response shape; delegate to codex parser.
func ExtractUsage(raw []byte) (metering.UsageDelta, error) {
	return codex.ExtractUsage(raw)
}

func SessionHookEnabled() bool { return true }

func RecordResponse(raw []byte) {
	codex.RecordResponse(raw)
}

