// Code generated by generate-agent-metering.sh — DO NOT EDIT by hand.
// Regenerate from the delta package after updating provider shapes.
package kilocode


import (
	"encoding/json"

	"github.com/rd-mg/architect-ai/internal/metering"
)

type kilocodeUsageEnvelope struct {
	Usage struct {
		PromptTokens     int64 `json:"prompt_tokens"`
		CompletionTokens int64 `json:"completion_tokens"`
		CachedTokens     int64 `json:"cached_tokens"`
	} `json:"usage"`
	Model string `json:"model"`
}

func ExtractUsage(raw []byte) (metering.UsageDelta, error) {
	var env kilocodeUsageEnvelope
	if err := json.Unmarshal(raw, &env); err != nil {
		return metering.UsageDelta{}, err
	}
	return metering.UsageDelta{
		PromptTokens:     env.Usage.PromptTokens,
		CompletionTokens: env.Usage.CompletionTokens,
		CachedTokens:     env.Usage.CachedTokens,
		Model:            env.Model,
	}, nil
}

func SessionHookEnabled() bool { return true }

func RecordResponse(raw []byte) {
	hook := metering.Current()
	if hook == nil {
		return
	}
	delta, err := ExtractUsage(raw)
	if err != nil {
		return
	}
	hook.Record(delta)
}

