// Code generated by generate-agent-metering.sh — DO NOT EDIT by hand.
// Regenerate from the delta package after updating provider shapes.
package windsurf


import (
	"github.com/rd-mg/architect-ai/internal/metering"
)

// Windsurf does not expose usage through the architect-ai CLI path.
func ExtractUsage(_ []byte) (metering.UsageDelta, error) {
	return metering.UsageDelta{}, nil
}

func SessionHookEnabled() bool { return false }

func RecordResponse(_ []byte) {}

