#!/usr/bin/env bash
# GGA v2.0 — generated by architect-ai gga install
# Pre-commit hook: static checks always, AI audit when available

set -euo pipefail

GGA_VERSION="2.0"
GGA_ENDPOINT="${GGA_ENDPOINT:-http://localhost:8765/audit}"
GGA_TIMEOUT="${GGA_TIMEOUT:-15}"

# ── Environment detection ─────────────────────────────────────────────────────

# Detect CI environment — AI audit may not be available
IS_CI="${CI:-false}"
if [ "${IS_CI}" = "true" ] || [ -n "${GITHUB_ACTIONS:-}" ] || [ -n "${GITLAB_CI:-}" ]; then
  GGA_CI_MODE=true
else
  GGA_CI_MODE=false
fi

# Detect Odoo project
IS_ODOO="false"
ODOO_VERSION="unknown"
MANIFEST=$(find . -name "__manifest__.py" -maxdepth 5 | head -1 2>/dev/null)
if [ -n "${MANIFEST}" ]; then
  IS_ODOO="true"
  ODOO_VERSION=$(python3 -c "
import re
try:
    txt = open('${MANIFEST}').read()
    m = re.search(r'[\"\\x27]version[\"\\x27]\\s*:\\s*[\"\\x27](\\d+)\\.', txt)
    print(m.group(1) if m else 'unknown')
except: print('unknown')
" 2>/dev/null || echo "unknown")
fi
[ -f "requirements.txt" ] && grep -q "^odoo" requirements.txt 2>/dev/null && IS_ODOO="true"

# Detect cudio-git rules
HAS_CUDIO_GIT="false"
[ -f ".atl/overlays/odoo-development-skill/rules/cudio-git.md" ] && HAS_CUDIO_GIT="true"
[ -f "cudio-git.md" ] && HAS_CUDIO_GIT="true"

# ── Staged diff + commit message ──────────────────────────────────────────────

DIFF=$(git diff --cached --unified=3 2>/dev/null || echo "")
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
COMMIT_MSG_FILE="${GIT_DIR:-$(git rev-parse --git-dir 2>/dev/null || echo .git)}/COMMIT_EDITMSG"
COMMIT_MSG=$(cat "${COMMIT_MSG_FILE}" 2>/dev/null | head -1 || echo "")

# ── ALWAYS: Secret detection (never skippable) ────────────────────────────────

SECRET_PATTERNS=(
  '(api_key|secret|password|token|private_key)\s*=\s*["'"'"'][^"'"'"']{8,}'
  'AKIA[0-9A-Z]{16}'
  'ghp_[a-zA-Z0-9]{36}'
  'sk-[a-zA-Z0-9]{48}'
  '-----BEGIN (RSA|EC|OPENSSH) PRIVATE KEY-----'
)

for pattern in "${SECRET_PATTERNS[@]}"; do
  if echo "${DIFF}" | grep -qE "${pattern}" 2>/dev/null; then
    echo "GGA: ⛔ BLOCKED — credential pattern detected in staged changes" >&2
    echo "GGA: Pattern matched: ${pattern}" >&2
    echo "GGA: Remove credentials before committing. Use environment variables." >&2
    exit 1
  fi
done

# Detect staged .env files
if git diff --cached --name-only | grep -qE '\.env($|\.)'; then
  echo "GGA: ⛔ BLOCKED — .env file staged for commit" >&2
  echo "GGA: Add .env to .gitignore and use .env.example instead." >&2
  exit 1
fi

# ── Skip-AI mode ──────────────────────────────────────────────────────────────

if [ "${GGA_SKIP:-0}" = "1" ] || [ "${1:-}" = "--skip-ai" ]; then
  echo "GGA: ⚡ skip-ai mode. Static checks passed."
  mkdir -p .gga
  # Write skip log (durable — also save to Engram if available)
  LOG_ENTRY="{\"ts\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"branch\":\"${BRANCH}\",\"commit\":\"${COMMIT_MSG:0:72}\",\"reason\":\"${GGA_SKIP_REASON:-unspecified}\"}"
  echo "${LOG_ENTRY}" >> .gga/skip-log.jsonl

  # Save to Engram for durable audit trail (non-blocking)
  if command -v engram > /dev/null 2>&1; then
    ENGRAM_BIN="${ENGRAM_BIN:-engram}"
    "${ENGRAM_BIN}" save \
      --key "gga/skip-log/$(date +%Y%m%d-%H%M%S)" \
      --content "${LOG_ENTRY}" \
      --project "${GGA_PROJECT:-$(basename "$(git rev-parse --show-toplevel 2>/dev/null || echo unknown)")" \
      2>/dev/null || true  # non-blocking
  fi
  exit 0
fi

# ── CI mode: static-only (no AI call) ────────────────────────────────────────

if [ "${GGA_CI_MODE}" = "true" ]; then
  echo "GGA: 🤖 CI environment detected. Running static checks only (no AI call)."
  # Static checks already ran above (secrets)
  echo "GGA: ✅ Static checks passed in CI mode."
  exit 0
fi

# ── AI Audit ──────────────────────────────────────────────────────────────────

# Build payload using printf to avoid jq dependency
PAYLOAD=$(python3 -c "
import json, sys
payload = {
  'diff': sys.argv[1][:50000],  # truncate large diffs
  'commit_msg': sys.argv[2],
  'branch': sys.argv[3],
  'is_odoo': sys.argv[4] == 'true',
  'odoo_version': sys.argv[5],
  'has_cudio_git': sys.argv[6] == 'true'
}
print(json.dumps(payload))
" "${DIFF}" "${COMMIT_MSG}" "${BRANCH}" "${IS_ODOO}" "${ODOO_VERSION}" "${HAS_CUDIO_GIT}" 2>/dev/null)

# AI call with timeout and non-blocking fallback
RESPONSE=$(curl -sf \
  --max-time "${GGA_TIMEOUT}" \
  --connect-timeout 5 \
  -H "Content-Type: application/json" \
  -d "${PAYLOAD}" \
  "${GGA_ENDPOINT}" 2>/dev/null) || {
    echo "GGA: ⚠️ AI provider unavailable (timeout or connection refused)."
    echo "GGA: Running static-only mode. Commit proceeds."
    mkdir -p .gga
    echo "{\"ts\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"error\":\"provider_unavailable\",\"branch\":\"${BRANCH}\"}" >> .gga/provider-errors.jsonl
    exit 0  # non-blocking when AI unavailable
}

# Parse verdict
VERDICT=$(python3 -c "import sys,json; print(json.loads(sys.argv[1]).get('verdict','APPROVE'))" "${RESPONSE}" 2>/dev/null || echo "APPROVE")
SUMMARY=$(python3 -c "import sys,json; print(json.loads(sys.argv[1]).get('summary',''))" "${RESPONSE}" 2>/dev/null || echo "")

case "${VERDICT}" in
  BLOCK)
    echo "GGA: ⛔ BLOCKED — ${SUMMARY}" >&2
    python3 -c "
import sys, json
data = json.loads(sys.argv[1])
for f in data.get('findings', []):
    if f.get('severity') in ['CRITICAL', 'HIGH']:
        loc = f.get('file', '?')
        line = f.get('line', '?')
        print(f'  [{f[\"severity\"]}] {loc}:{line} — {f[\"message\"]}', file=sys.stderr)
" "${RESPONSE}" >&2
    exit 1
    ;;
  WARN)
    echo "GGA: ⚠️ WARNING — ${SUMMARY}"
    python3 -c "
import sys, json
data = json.loads(sys.argv[1])
for f in data.get('findings', []):
    print(f'  [{f[\"severity\"]}] {f[\"message\"]}')
" "${RESPONSE}"
    exit 0
    ;;
  *)
    echo "GGA: ✅ APPROVED — ${SUMMARY:-No issues found.}"
    exit 0
    ;;
esac
