// Code generated by generate-agent-metering.sh — DO NOT EDIT by hand.
// Regenerate from the delta package after updating provider shapes.
package vscode


import (
	"github.com/rd-mg/architect-ai/internal/metering"
)

// VSCode does not expose usage directly through the architect-ai CLI path.
// Metering is a no-op.
func ExtractUsage(_ []byte) (metering.UsageDelta, error) {
	return metering.UsageDelta{}, nil
}

func SessionHookEnabled() bool { return false }

func RecordResponse(_ []byte) {}

